"""Query Engine - Natural language to SQL converter."""

from query_engine.config import QueryEngineConfig
from query_engine.engine import QueryEngine
from query_engine.llm.client import LLMClient, anthropic_client, openai_client
from query_engine.types import (
    ColumnInfo,
    ConversationResponse,
    ConversationTurn,
    DataSourceSchema,
    DataSourceType,
    DebugInfo,
    ExampleQuery,
    QueryResponse,
    SQLValidationResult,
    TableInfo,
)
from query_engine.utils import (
    AmbiguityResolutionError,
    APIAuthenticationError,
    APIError,
    APIParsingError,
    APIRateLimitError,
    APIUnavailableError,
    ConfigurationError,
    ConversationError,
    DataFormatError,
    DataSourceError,
    DebugFailedError,
    FileNotFoundError,
    QueryEngineError,
    QueryExecutionError,
    QueryTimeoutError,
    SchemaError,
    SQLSafetyError,
    SQLSchemaError,
    SQLSyntaxError,
    get_logger,
    setup_logging,
)

__version__ = "0.1.0"

__all__ = [
    "APIAuthenticationError",
    "APIError",
    "APIParsingError",
    "APIRateLimitError",
    "APIUnavailableError",
    "AmbiguityResolutionError",
    "ColumnInfo",
    "ConfigurationError",
    "ConversationError",
    "ConversationResponse",
    "ConversationTurn",
    "DataFormatError",
    "DataSourceError",
    "DataSourceSchema",
    "DataSourceType",
    "DebugFailedError",
    "DebugInfo",
    "ExampleQuery",
    "FileNotFoundError",
    "LLMClient",
    "QueryEngine",
    "QueryEngineConfig",
    "QueryEngineError",
    "QueryExecutionError",
    "QueryResponse",
    "QueryTimeoutError",
    "SQLSafetyError",
    "SQLSchemaError",
    "SQLSyntaxError",
    "SQLValidationResult",
    "SchemaError",
    "TableInfo",
    "anthropic_client",
    "get_logger",
    "openai_client",
    "setup_logging",
]
